spring:
  application:
    name: ic-partner-sender
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:30179"
        bindings:
          partner-data-out:
            producer:
              configuration:
                key.serializer: org.springframework.kafka.support.serializer.ToStringSerializer
                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
                spring.json.add.type.headers: false
      bindings:
        partner-data-out:
          producer:
            # use kafka internal encoding
            useNativeEncoding: true
          destination: partner-topic